// FAKE DISCORD VZLOM BY SGYSH3NKA
console.log("Hacking random user")
wait(5000)
console.log("Checking.")
wait(500)
console.log("Checking..")
wait(500)
console.log("Checking...")
wait(500)
console.log("Checking.")
wait(500)
console.log("Checking..")
wait(500)
console.log("Checking...")
wait(500)
console.log("Hacked!")
console.log("login=error")
console.log("password=api is down")
